server:
  port: 9090

mybatis:
  typeAliasesPackage: com.tml.mouseDemo.model
  mapperLocations: classpath:mapper/*.xml

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db_users;MODE=MYSQL;INIT=RUNSCRIPT FROM 'classpath:sql/init.sql'
    username: tml
    password: helloTml
  h2:
    console:
      enabled: true

  logging:
    level:
      com.tml.mouseDemo.data.*: debug
    config: classpath:logback.xml
