server:
  port: 9090

mybatis:
  typeAliasesPackage: com.tml.mouseDemo.model
  mapperLocations: classpath:mapper/*.xml

spring:
  datasource:
    data1:
      jdbc-url: jdbc:mysql://localhost:3306/tml?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
    data2:
      jdbc-url: jdbc:mysql://localhost:3306/mouse?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
