server:
  port: 9090

mybatis:
  typeAliasesPackage: com.tml.mouseDemo.model
  mapperLocations: classpath:mapper/*.xml

spring:
  datasource:
    data1:
      url: jdbc:mysql://47.106.169.177:3306/tml?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
      username: root
      password: mouseCat
      driver-class-name: com.mysql.jdbc.Driver
    data2:
      url: jdbc:mysql://47.106.169.177:3306/mouse?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
      username: root
      password: mouseCat
      driver-class-name: com.mysql.jdbc.Driver
